### ISSUE TITLE
Conda package not found

### ISSUE THREAD

**Issue by maximlamare** [dcs4cop/xcube-geodb#3]
Hello,

There seems to be a typo in your documentation. The documentation specifies to install xcube-geodb using: `conda install -c conda-forge xcube-geodb`

However, this command fails:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - xcube-geodb
[...]
```
On the other hand, the command `conda install -c conda-forge xcube_geodb` works.

**Comment by dzelge** [comment]
Apologies: It should be xcube_geodb. Conda forge does that when it names the feedstock repo.
