### ISSUE TITLE
GeoDBClient: Missing auth0 config results in FileExistsError, not FileNotFoundError

### ISSUE THREAD

**Issue by pont-us** [dcs4cop/xcube-geodb#5]
[GeoDBClient._auth0_login](https://github.com/dcs4cop/xcube-geodb/blob/master/xcube_geodb/core/geodb.py#L251) raises a rather counterintuitive exception if the auth0 configuration file is not found:

```
        if not os.path.isfile(os.path.join(auth0_config_folder, auth0_config_file)):
            raise FileExistsError("Mandatory auth configuration file ipyauth-auth0-demo.env must exist")
```

The Python docs say that [FileExistsError](https://docs.python.org/3/library/exceptions.html#FileExistsError) is raised "when trying to create a file or directory which already exists", which is not appropriate here. This, surely, should rather be a [FileNotFoundError](https://docs.python.org/3/library/exceptions.html#FileNotFoundError).

**Comment by thomasstorm** [comment]
These line have been removed already with commit 22fa37281375aac62623b42b65d1f087cce6f2a6
